/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTheoryRouteImport } from './routes/_app/theory'
import { Route as AppSolverRouteImport } from './routes/_app/solver'
import { Route as AppPartialDerivativesRouteImport } from './routes/_app/partial-derivatives'
import { Route as AppExamplesRouteImport } from './routes/_app/examples'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppQuizzesIndexRouteImport } from './routes/_app/quizzes/index'
import { Route as AppQuizzesDifficultyIdRouteImport } from './routes/_app/quizzes/$difficulty/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTheoryRoute = AppTheoryRouteImport.update({
  id: '/theory',
  path: '/theory',
  getParentRoute: () => AppRoute,
} as any)
const AppSolverRoute = AppSolverRouteImport.update({
  id: '/solver',
  path: '/solver',
  getParentRoute: () => AppRoute,
} as any)
const AppPartialDerivativesRoute = AppPartialDerivativesRouteImport.update({
  id: '/partial-derivatives',
  path: '/partial-derivatives',
  getParentRoute: () => AppRoute,
} as any)
const AppExamplesRoute = AppExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesIndexRoute = AppQuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuizzesDifficultyIdRoute = AppQuizzesDifficultyIdRouteImport.update({
  id: '/quizzes/$difficulty/$id',
  path: '/quizzes/$difficulty/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/examples': typeof AppExamplesRoute
  '/partial-derivatives': typeof AppPartialDerivativesRoute
  '/solver': typeof AppSolverRoute
  '/theory': typeof AppTheoryRoute
  '/quizzes/': typeof AppQuizzesIndexRoute
  '/quizzes/$difficulty/$id': typeof AppQuizzesDifficultyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/examples': typeof AppExamplesRoute
  '/partial-derivatives': typeof AppPartialDerivativesRoute
  '/solver': typeof AppSolverRoute
  '/theory': typeof AppTheoryRoute
  '/quizzes': typeof AppQuizzesIndexRoute
  '/quizzes/$difficulty/$id': typeof AppQuizzesDifficultyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/examples': typeof AppExamplesRoute
  '/_app/partial-derivatives': typeof AppPartialDerivativesRoute
  '/_app/solver': typeof AppSolverRoute
  '/_app/theory': typeof AppTheoryRoute
  '/_app/quizzes/': typeof AppQuizzesIndexRoute
  '/_app/quizzes/$difficulty/$id': typeof AppQuizzesDifficultyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/examples'
    | '/partial-derivatives'
    | '/solver'
    | '/theory'
    | '/quizzes/'
    | '/quizzes/$difficulty/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/examples'
    | '/partial-derivatives'
    | '/solver'
    | '/theory'
    | '/quizzes'
    | '/quizzes/$difficulty/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/examples'
    | '/_app/partial-derivatives'
    | '/_app/solver'
    | '/_app/theory'
    | '/_app/quizzes/'
    | '/_app/quizzes/$difficulty/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/theory': {
      id: '/_app/theory'
      path: '/theory'
      fullPath: '/theory'
      preLoaderRoute: typeof AppTheoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/solver': {
      id: '/_app/solver'
      path: '/solver'
      fullPath: '/solver'
      preLoaderRoute: typeof AppSolverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partial-derivatives': {
      id: '/_app/partial-derivatives'
      path: '/partial-derivatives'
      fullPath: '/partial-derivatives'
      preLoaderRoute: typeof AppPartialDerivativesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/examples': {
      id: '/_app/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof AppExamplesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quizzes/': {
      id: '/_app/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof AppQuizzesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quizzes/$difficulty/$id': {
      id: '/_app/quizzes/$difficulty/$id'
      path: '/quizzes/$difficulty/$id'
      fullPath: '/quizzes/$difficulty/$id'
      preLoaderRoute: typeof AppQuizzesDifficultyIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppExamplesRoute: typeof AppExamplesRoute
  AppPartialDerivativesRoute: typeof AppPartialDerivativesRoute
  AppSolverRoute: typeof AppSolverRoute
  AppTheoryRoute: typeof AppTheoryRoute
  AppQuizzesIndexRoute: typeof AppQuizzesIndexRoute
  AppQuizzesDifficultyIdRoute: typeof AppQuizzesDifficultyIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppExamplesRoute: AppExamplesRoute,
  AppPartialDerivativesRoute: AppPartialDerivativesRoute,
  AppSolverRoute: AppSolverRoute,
  AppTheoryRoute: AppTheoryRoute,
  AppQuizzesIndexRoute: AppQuizzesIndexRoute,
  AppQuizzesDifficultyIdRoute: AppQuizzesDifficultyIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
